---
#
# Playbook to install the ELK stack
#
- hosts: elk
 remote_user: ansible
 become: yes
 become_user: root
 roles:
   - { role: java }
   - { role: elasticsearch }
   - { role: kibana }
   - { role: nginx }
   - { role: logstash }
