--- 
- 
  apt_repository: 
    repo: "ppa:webupd8team/java"
  name: "Add Java repository"
- 
  name: "Automatically select the Oracle License"
  shell: "echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections"
- 
  apt: 
    name: oracle-java8-installer
    state: present
    update_cache: no
  name: "Install the Java 8 package"
