--- 
- 
  apt_repository: 
    repo: "ppa:webupd8team/java"
  name: "Add Java repository"
- 
  name: "Automatically select the Oracle License"
  shell: "echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections"
- 
  apt: 
    name: oracle-java8-installer
    state: present
    update_cache: false
  name: "Install the Java 8 package"
- 
  lineinfile: "dest=/etc/environment regexp='' insertafter=EOF line=\"JAVA_HOME=/usr/lib/jvm/default-java\""
  name: "Set JAVA_HOME"
- 
  action: "shell /usr/bin/java -version"
  changed_when: false
  name: "Verify Java Version"
  register: java
  tags: 
    - verify
